from aiogram.dispatcher.filters.state import StatesGroup, State

class Translate(StatesGroup):
    hotdogset=State()
    shavermaset=State()
    somsaset=State()
    lavashset=State()
    gamburgerset=State()
    pitsaset=State()
    colaset=State()
    fantaset=State()
    pepsiset=State()
    spriteset=State()
    pitsabuyurtma=State()
    hotdogbuyurtma=State()
    shavermabuyurtma=State()
    somsabuyurtma=State()
    lavashbuyurtma=State()
    gamburgerbuyurtma=State()
    # pitsaset=State()
    colabuyurtma=State()
    fantabuyurtma=State()
    pepsibuyurtma=State()
    spritebuyurtma=State()
    raqam=State()
    manzil=State()
